name: spacepong
version: '3.8'

services:
  frontend:
    build: # 도커 이미지 빌드를 위한 Dockerfile의 경로
      context: ./frontend
    init: true
    ports: # 사용할 포트 번호 ([Host port]:[Container port])
      - "443:443"
    restart: always
    depends_on: # 먼저 실행되고 있어야 하는 의존 서비스(컨테이너)
      - backend
    volumes: # 컨테이너의 데이터가 저장될 Host 디렉토리 ([Host 디렉토리]:[Container 디렉토리])
      - ./frontend/srcs:/var/www/html
    networks: # 연결될 도커 네트워크
      - spacepong-net

  backend:
    build:
      context: ./backend
    init: true
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - ./.env
    depends_on:
      - db
    volumes:
      - ./backend/srcs:/app
    networks:
      - spacepong-net

  db:
    build:
      context: ./db
    init: true
    expose:
      - "5432"
    restart: always
    env_file: 
      - ./.env
    networks:
      - spacepong-net

networks:
  spacepong-net:
