name: spacepong
version: '3.8'

services:
  ### WEB ###
  frontend:
    build: # 도커 이미지 빌드를 위한 Dockerfile의 경로
      context: ./frontend
      args: # .env 파일의 환경 변수를 dockerfile에 전달
        ELASTIC_USER: ${ELASTIC_USER}
        ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
    container_name: frontend
    env_file:
      - ./.env
    init: true
    ports: # 사용할 포트 번호 ([Host port]:[Container port])
      - "443:443"
    restart: always
    depends_on: # 먼저 실행되고 있어야 하는 의존 서비스(컨테이너)
      - backend
    volumes: # 컨테이너의 데이터가 저장될 Host 디렉토리 ([Host 디렉토리]:[Container 디렉토리])
      - ./frontend/srcs:/var/www/html
    networks: # 연결될 도커 네트워크
      - spacepong-net

  backend:
    build:
      context: ./backend
    container_name: backend
    env_file:
      - ./.env
    init: true
    ports:
      - "8000:8000"
      - "587:587"
    restart: always
    depends_on:
      - db
    volumes:
      - ./backend/srcs:/app
    networks:
      - spacepong-net

  db:
    build:
      context: ./db
    container_name: db
    env_file:
      - ./.env
    init: true
    expose:
      - "5432"
    restart: always
    env_file: 
      - ./.env
    networks:
      - spacepong-net

  ### ELK ###
  elasticsearch:
    build:
      context: ./elk/elasticsearch
    container_name: elasticsearch
    env_file:
      - ./.env
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=true
      - xpack.license.self_generated.type=basic
      - ELASTIC_USERNAME=${ELASTIC_USER}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    expose:
      - "9200"
    networks:
      - spacepong-net

  # logstash:
  #   build:
  #     context: ./elk/logstash
  #   container_name: logstash
  #   env_file:
  #     - ./.env
  #   expose:
  #     - "5044"
  #   networks:
  #     - spacepong-net

  kibana:
    build:
      context: ./elk/kibana
    container_name: kibana
    env_file:
      - ./.env
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=${ELASTIC_USER}
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
    ports:
      - "5601:5601"
    networks:
      - spacepong-net

networks:
  spacepong-net:
