# Generated by Django 4.2.11 on 2024-05-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IsMatched', models.BooleanField(default=False)),
                ('RoomNumber', models.CharField(max_length=100)),
                ('myName', models.CharField(max_length=100)),
                ('oppositeName', models.CharField(max_length=100)),
                ('hostName', models.CharField(max_length=100)),
                ('gusetName', models.CharField(max_length=100)),
                ('mySkin', models.CharField(max_length=100)),
                ('oppositeSkin', models.CharField(max_length=100)),
            ],
        ),
    ]
