# Generated by Django 4.2.11 on 2024-05-24 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spacepong', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamedata',
            old_name='gusetName',
            new_name='guestName',
        ),
    ]
