# Generated by Django 4.2.11 on 2024-05-24 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth42', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
